//
//  MainRequest.swift
//  TestingTwitch
//
//  Created by Pavel Zveglyanich on 7/6/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Alamofire

enum MainRequest {
    case someMain
}

extension MainRequest/*: DefaultRequest*/ {
    var path: String {
        switch self {
        case .someMain:
            return "v1/REPLACE_WITH_PATH/"
        }
    }
    
    var method: HTTPMethod {
        switch self {
        case .someMain:
            return .get
        }
    }
    
    var headers: HTTPHeaders {
        let token = "token"//try! KeychainManager().getToken()
        return [
            "Authorization": "JWT \(token)",
            "Content-Type": "application/json",
        ]
    }
    
    var parameters: [String: Any]? {
        switch self {
        case .someMain:
            return nil
        }
    }
}
