//
//  MainViewController.swift
//  TestingTwitch
//
//  Created by Pavel Zveglyanich on 7/6/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol MainDisplayLogic: class {
    func displaySomething()
}

class MainViewController: UIViewController {
    var presenter: MainViewControllerOutput!

	var tableView: UITableView = {
		let table = UITableView()
		table.separatorStyle = .none
		table.backgroundColor = .white
		table.sectionFooterHeight = 0
		return table
	}()
	
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
		setupConstraints()
    }
    
    // MARK: Action
    
    func someAction() {
        presenter.someActionTriggered()
    }
}

// MARK: Setup
private extension MainViewController {
    func setup() {
		view.backgroundColor = .white
		view.addSubview(tableView)
		setupCells()
		tableView.delegate = self
		tableView.dataSource = self
    }
	func setupConstraints() {
		tableView.snp.makeConstraints({ make in
			make.left.top.right.bottom.equalToSuperview()
		})
	}
	func setupCells() {
		tableView.register(DefaultMainTableViewCell.self, forCellReuseIdentifier: String(describing: DefaultMainTableViewCell.self))
	}
}

extension MainViewController: MainDisplayLogic {
    func displaySomething() {
    }
}

extension MainViewController: UITableViewDelegate {
	func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
		//presenter?.routeToObject(by: indexPath)
	}
	
	func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
		return DefaultMainTableViewCell.height//indexPath.row >= viewModel!.count ? MyAdsLoadingTableViewCell.height : MyAdsTableViewCell.height
	}
	
	func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
		cell.backgroundColor = .clear
		cell.selectionStyle = .none
	}
	
}
extension MainViewController: UITableViewDataSource {
	
	func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
		return 10
	}
	
	func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
		let cell = tableView.dequeueReusableCell(withIdentifier: String(describing: DefaultMainTableViewCell.self), for: indexPath) as! DefaultMainTableViewCell
		return cell
	}
	
	
}
