//
//  MainRouter.swift
//  TestingTwitch
//
//  Created by Pavel Zveglyanich on 7/6/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainRoutingLogic {
    func routeTo(target: MainRouter.Targets)
}

class MainRouter: MainRoutingLogic {

    private var navigationController: UINavigationController?
    init(withNavigationController: UINavigationController?) {
        self.navigationController = withNavigationController
    }

    enum Targets {
        case t1
        // ...
    }

    func routeTo(target: MainRouter.Targets) {
        switch target {
        case .t1:
            print(#function)
            /*let someVC = SomeVC(nibName: someVC.kStoryboardID, bundle: nil)
             SomeConfigurator().configure(viewController: someVC, navigationController: self.navigationController)
            navigationController?.pushViewController(someVC, animated: true)*/
        }
    }
}
