//
//  MainViewController.swift
//  TestingTwitch
//
//  Created by Pavel Zveglyanich on 7/6/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol MainDisplayLogic: class {
	func addViewModelAt(_ viewModel: [DataModel]?)
}

class MainViewController: UIViewController {
    var presenter: MainViewControllerOutput?
	private var viewModel: [DataModel]?
	
	var tableView: UITableView = {
		let table = UITableView()
		table.separatorStyle = .none
		table.backgroundColor = .white
		table.sectionFooterHeight = 0
		return table
	}()

    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
		setupConstraints()
    }
}

private extension MainViewController {
    func setup() {
		
		let feedBackBarButtonItem = UIBarButtonItem(image: UIImage(systemName: "star.square.fill"), style: UIBarButtonItem.Style.done, target: self, action: #selector(openFeedBackViewController))
		feedBackBarButtonItem.tintColor = .blue
		navigationItem.setRightBarButtonItems([feedBackBarButtonItem], animated: true)
		
		view.backgroundColor = .white
		view.addSubview(tableView)
		setupCells()
		presenter?.getViewModel()
		tableView.delegate = self
		tableView.dataSource = self
    }
	func setupConstraints() {
		tableView.snp.makeConstraints({ make in
			make.left.top.right.bottom.equalToSuperview()
		})
	}
	func setupCells() {
		tableView.register(DefaultMainTableViewCell.self, forCellReuseIdentifier: String(describing: DefaultMainTableViewCell.self))
	}
	
	@objc private func openFeedBackViewController() {
		presenter?.openFeedBackViewController()
	}
}

extension MainViewController: MainDisplayLogic {
	func addViewModelAt(_ viewModel: [DataModel]?) {
		guard let model = viewModel else { return }
		if self.viewModel == nil {
			self.viewModel = model
		} else {
			self.viewModel?.append(contentsOf: model)
		}
		tableView.reloadData()
	}

}

extension MainViewController: UITableViewDelegate {
	
	func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
		guard viewModel != nil else { return 0 }
		return indexPath.row >= viewModel!.count  ? DefaultMainTableViewCell.height : DefaultMainTableViewCell.height
	}
	
	func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
		cell.backgroundColor = .clear
		cell.selectionStyle = .none
	}
	func scrollViewDidScroll(_ scrollView: UIScrollView) {
		let position = scrollView.contentOffset.y
		
		if position > (tableView.contentSize.height - scrollView.frame.size.height) {
			DispatchQueue.global(qos: .background).async {
				self.presenter?.getViewModel()
			}
		}
	}
	
}

extension MainViewController: UITableViewDataSource {
	
	func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
		guard let section = viewModel?.count else { return 0 }
		return section
	}
	
	func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
		guard let viewObjects = viewModel else { return UITableViewCell() }
		let cell = tableView.dequeueReusableCell(withIdentifier: String(describing: DefaultMainTableViewCell.self), for: indexPath) as! DefaultMainTableViewCell
		cell.configure(with: viewObjects[indexPath.row])
		return cell
	}
}
