//
//  MainInteractor.swift
//  TestingTwitch
//
//  Created by Pavel Zveglyanich on 7/6/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol MainBusinessLogic {
    func downloadDataModel(completion: @escaping (_ succsess: Bool, _ dataModel: [DataModel]?, _ error: Error?) -> ())
}

protocol MainDataStore {

    var dataModel: [DataModel]? { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
	
	///Текущая страница
	private var page = 0
	private let pageStep = 10
	
	var dataModel: [DataModel]?
	
	func downloadDataModel(completion: @escaping (Bool, [DataModel]?, Error?) -> ()) {
		let downloadingPage = (page + 1) * pageStep
		NetworkManager.shared.request(MainRequest.someMain(pageNumber: downloadingPage)) { [weak self] Result in
			switch Result {
			case .success(let data):
				guard let dataModel = data else { return }
				
				if self?.dataModel == nil {
					self?.dataModel = dataModel
				} else {
					self?.dataModel?.append(contentsOf: dataModel)
				}
				completion(true, self?.dataModel, nil)
			case .failure(let error):
				completion(false, nil, error)
			}
		}
	}
	
	
    weak var presenter: MainPresentationLogic!
    var worker: MainWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething() {
        worker = MainWorker()
        worker?.doSomeWork()
        
    }
}
