//
//  MainRouter.swift
//  TestingTwitch
//
//  Created by Pavel Zveglyanich on 7/6/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainRoutingLogic {
    func routeTo(target: MainRouter.Targets)
}

class MainRouter: MainRoutingLogic {

    private var navigationController: UINavigationController?
    init(withNavigationController: UINavigationController?) {
        navigationController = withNavigationController
    }

    enum Targets {
        case feedback
    }

    func routeTo(target: MainRouter.Targets) {
        switch target {
        case .feedback:
            print(#function)
			let feedBackVC = FeedbackViewController()
            navigationController?.pushViewController(feedBackVC, animated: true)
        }
    }
}
