//
//  MainPresenter.swift
//  TestingTwitch
//
//  Created by Pavel Zveglyanich on 7/6/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainViewControllerOutput {
	func getViewModel()
	func openFeedBackViewController()
}

class MainPresenter {

    var interactor: MainBusinessLogic?
    weak var viewController: MainDisplayLogic?
    var router: MainRoutingLogic?
    
}

extension MainPresenter: MainViewControllerOutput {
	func openFeedBackViewController() {
		router?.routeTo(target: .feedback)
	}
	
	func getViewModel() {
		interactor?.downloadDataModel { [weak self] succsess, model, error in
			if succsess {
				self?.viewController?.addViewModelAt(model)
			} else {
				print ("viewController.displayErrorAlert(message: message, errorCode: errorCode, error: error)")
			}
		}
	}
}
