//
//  MainConfigurator.swift
//  TestingTwitch
//
//  Created by Pavel Zveglyanich on 7/6/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/*
 protocol BaseConfiguratorProtocol {
 func configure(viewController: UIViewController, navigationController: UINavigationController?)
 }
 */

final class MainConfigurator: BaseConfiguratorProtocol {
    func configure(viewController: UIViewController, navigationController: UINavigationController?) {
        let viewController = viewController as! MainViewController
        
        let presenter = MainPresenter()
        let interactor = MainInteractor()
        let router = MainRouter(withNavigationController: navigationController)

        
        //interactor.presenter = presenter
        viewController.presenter = presenter
        presenter.viewController = viewController
        presenter.interactor = interactor
        presenter.router = router
    }
}
