//
//  MainRequest.swift
//  TestingTwitch
//
//  Created by Pavel Zveglyanich on 7/6/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Alamofire

enum MainRequest {
    case someMain
}

extension MainRequest: DefaultRequest {
    var path: String {
        switch self {
        case .someMain:
            return "/kraken/games/top"
        }
    }
    
    var method: HTTPMethod {
        switch self {
        case .someMain:
            return .get
        }
    }
    
    var headers: HTTPHeaders {
		let clientID = GlobalConsts.ClientID
		let accept = GlobalConsts.accept
        return [
			"Accept": "\(accept)",
			"Client-ID": "\(clientID)"
        ]
    }
    
    var parameters: [String: Any]? {
        switch self {
        case .someMain:
            return nil
        }
    }
}


protocol DefaultRequest: URLRequestConvertible {
	var path: String { get }
	var method: HTTPMethod { get }
	var headers: HTTPHeaders { get }
	var parameters: [String: Any]? { get }
}

extension DefaultRequest {
	func asURLRequest() throws -> URLRequest {
		let url = try GlobalConsts.baseURL.asURL()
		var urlRequest = URLRequest(url: url.appendingPathComponent(path))
		urlRequest.httpMethod = method.rawValue
		urlRequest.allHTTPHeaderFields = headers
		
		return urlRequest
	}
}
